### ISSUE TITLE
ssc setup --platform=android causes Error: spawn powershell.exe ENOENT

### ISSUE THREAD

**Issue by mehdi-cit** [socketsupply/create-socket-app#41]
Hello,
I finally were able to run the desktop example on my windows machine yesterday after much help from @mribbons 
I did install all options and made sure I used paths with no spaces (everything under: **C:\root\.gradle** & **C:\root\Android** )
I also added to the PATH all of:
`
C:\root\Android\platform-tools
C:\root\Android\cmdline-tools\latest\bin
C:\root\Android\[A[BC\root\JAVA_HOME\jdk-19.0.2\bin
C:\root\.gradle\gradle-8.0.2\bin
`

However, when running 
C:\projects\app> **ssc setup --platform=android**
I get the error below:
`
# Checking build dependencies...
Error: spawn powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {   
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn powershell.exe',
  path: 'powershell.exe',
  spawnargs: [ '.\\bin\\install.ps1', '-fte:android' ]
}
` 
Similarly, running
 C:\projects\app> **ssc build --platform=android-emulator -r**
We also get the error below:
`
Error: spawn powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn powershell.exe',
  path: 'powershell.exe',
  spawnargs: [ '.\\bin\\install.ps1', '-fte:android' ]
}
` 

I spent more than an hour trying to fix this with no success. Any idea?
PS: The path to powershell is in the PATH env as expected!

**Comment by mehdi-cit** [comment]
If anyone is having a similar problem.
I'm able to advance further, I simply put the command line in package.json (under scripts). The previous error is no more.
BTW, here's the additional script I added:
`
    "android": "ssc setup --platform=android & ssc build --platform=android-emulator -r",
`
I invoke it with:
`
npm run android
`
I'm not out of the woods yet. Somehow it's re-downloading Android, Java and what not.... will come back here if I have more info!

**Comment by mehdi-cit** [comment]
Continuing with my tests under this thread in case it can help others.
As per the last message above. I tried to run:
**gradlew init**
After that I re-tried
**npm run android**
It went even further this time but still failed as shown below:
`
C:\Code\socketsupply-test>npm run android

> socketsupply-test@1.0.0 android
> ssc build --platform=android-emulator -r

• cleaned: C:\Code\socketsupply-test\build\android-emulator 2244ms
• package prepared 3896ms
• ran user build command 279ms
[=======================================] 100% Computing updates...


FAILURE: Build failed with an exception.

* What went wrong:
Cannot locate tasks that match ':app:bundleDebug' as task 'bundleDebug' not found in project ':app'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
• ERROR: failed to invoke gradlew :app:bundleDebug --warning-mode all command. 25411ms

C:\Code\socketsupply-test>
`

Important note. I started earlier to use the command line and no longer Powershell or the command line that comes with vscode. Apparently, Powershell is causing issues! Again, using the regular windows CMD to try and run this thing!

**Comment by mribbons** [comment]
Hi @mehdi-cit,
Good to know that you can build and run a windows app.

I appreciate the elbow grease you have put in to trying to get android to work. Let's rewind a little and try to resolve it using a different approach.

> I also added to the PATH all of:


Did an error prompt you to add the android paths to PATH, or were you just trying to avoid spaces? (See below)

(It looks as though your PATH now has non ascii characters (they show up as [?] for me in your post above). This could be affecting the execution of `powershell.exe`.)

`ssc` stores setup information in `.ssc.env`.

For node based apps, this file is stored under 
```bash
node_modules\@socketsupply\socket\node_modules\@socketsupply\socket-win32-x64\.ssc.env # (This depends on the platform you're building on)
```
There is one drawback of using `create-socket-app` instead of just using `npm i -g @socketsupply/socket`, for each new app, `ssc` will recreate `.ssc.env`, because the package is installed locally under the app - We will improve this behaviour in the future.

Now because you have installed Android SDK etc to non standard locations due to your username space issue, `ssc` won't find those tools in the default locations, so it will attempt to install them for you.

However, once `ssc` is installed, the space in path problem isn't an issue, because all calls using the paths in `.ssc.env` are properly escaped, eg Visual Studio clang path:
```
CXX="C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\x64\bin\clang++.exe"
```

Therefore, because you want to use the `create-socket-app` approach, I suggest that you accept the default paths during `ssc setup --platform=android`. This will mean that the paths are automatically located when you run `ssc setup` for any subsequent apps.

**Comment by mehdi-cit** [comment]
Ok, I did "swallow" my pride and created a new admin user on my machine (one that does not include white spaces).
I also, added some info to the path and .env variables as showin in picture below
![image](https://github.com/socketsupply/create-socket-app/assets/2162107/2c24b42c-9824-4a23-8732-1ba044840314)
NB: I had to download and install **gradle** manually!
Re-created a new project following the guides.
Basically:
>>  npm i @socketsupply/socket -g
>>Start-Process powershell -verb runas -wait -ArgumentList "Set-ExecutionPolicy Bypass -Force"
>> npx create-socket-app react 
After that I ran the default script (to have the desktop version running)
>> npm start
So far so good, it does work and I'm able to see the app running! **Hello, win 32!**
Now comes the Android... what I'm really after :).
I edited scripts in **package.json** to add the following two lines

    "setup-android": "ssc setup --platform=android",
    "android": "ssc build --platform=android-emulator -r"
These two lines are mention under the same SocketSupply guides doc!
The first one runs without problem. The second one i.e.e **npm run android** fails with the output shown below


C:\Code\ss2>npm run android

> ss2@1.0.0 android
> ssc build --platform=android-emulator -r

• cleaned: C:\Code\ss2\build\android-emulator 1055ms
• package prepared 11300ms
• ran user build command 525ms
[=======================================] 100% Computing updates...

Downloading https://services.gradle.org/distributions/gradle-8.0.2-bin.zip
...........10%............20%............30%............40%............50%............60%...........70%............80%............90%............100%

FAILURE: Build failed with an exception.

* What went wrong:
Directory 'C:\Code\ss2' does not contain a Gradle build.

A Gradle build should contain a 'settings.gradle' or 'settings.gradle.kts' file in its root directory. It may also contain a 'build.gradle' or 'build.gradle.kts' file.

To create a new Gradle build in this directory run 'gradlew init'

For more detail on the 'init' task see https://docs.gradle.org/8.0.2/userguide/build_init_plugin.html

For more detail on creating a Gradle build see https://docs.gradle.org/8.0.2/userguide/tutorial_using_tasks.html

* Try:
> Run gradlew init to create a new Gradle build in this directory.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
• ERROR: failed to invoke gradlew :app:bundleDebug --warning-mode all command. 56668ms

**Comment by mribbons** [comment]
> Ok, I did "swallow" my pride and created a new admin user on my machine (one that does not include white spaces).

Sometimes it's good to test from a known working state (or environment in this case) :pray:

I believe you are now hitting an issue that was reported last week with our 0.3.1 release.
https://github.com/socketsupply/socket/issues/475

This will be fixed in the coming week with the 0.3.3 release.

For now, the best bet is to downgrade to 0.2.13:
```
# backup .ssc.env 
copy .\node_modules\@socketsupply\socket-win32-x64\.ssc.env .
yarn remove @socketsupply/socket
yarn add @socketsupply/socket@0.2.13
# redeploy .ssc.env 
copy . .\node_modules\@socketsupply\socket-win32-x64\.ssc.env
npm run android
```
Copying .ssc.env as above should prevent the Android First Time Experience process from running again.

**Comment by mribbons** [comment]
Just noting that @socketsupply/socket  v0.3.3 is up on npm, the gradlew issue has been resolved.

**Comment by mehdi-cit** [comment]
Fantastic, I will test Socket-Supply again whenever I have some free time

**Comment by lamiazar** [comment]
@mehdi-cit Thank you for providing details and contributing to fixing this issue.
